### ISSUE TITLE
Combining color and style ends up not showing prints correctly

### ISSUE THREAD

**Issue by Razican** [mackwic/colored#11]
As it can be seen [here](https://github.com/SUPERAndroidAnalyzer/super/issues/41), when combining styling and color in the same print, both color and style are reset when one of them stop, instead of returning to the color.

**Comment by mackwic** [comment]
Thank you for reporting the issue. Fixing it right now

**Comment by mackwic** [comment]
Fixed with PR #12

**Comment by Razican** [comment]
Seems that it's not completely fixed, I get this error:
![screenshot from 2016-11-08 20-15-26](https://cloud.githubusercontent.com/assets/597469/20113392/94d3a9c4-a5f0-11e6-976d-3105da45e907.png)

The code is the following:
```rust
print_error(format!("There was an error when executing the {} to {} conversion \
                                     command: {:?}",
                                    ".dex".italic(),
                                    ".jar".italic(),
                                    e))

/// Prints an error to `stderr` in red.
pub fn print_error<S: AsRef<str>>(error: S, verbose: bool) {
    let _ = io::stderr()
        .write(&format!("{} {}\n", "Error:".bold().red(), error.as_ref().red()).into_bytes()[..])
        .unwrap();
}
```

**Comment by mackwic** [comment]
Nice catch ! Thanks for the bug report.

I won't be able to work on it until next week or the week after. It should be solved quickly, though.

**Comment by mackwic** [comment]
I found the bug, it should be fixed, now 👍
